In [1]:
import torch

In [3]:
a = torch.randn((3, 4))

a.requires_grad_(True)

b = a.sum()

a.grad

In [4]:
b.backward()

In [5]:
a.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [3]:
x = torch.tensor([0., 3., 5.], requires_grad=True)
x

tensor([0., 3., 5.], requires_grad=True)

In [14]:
ex = x.exp()
y = ex / ex.sum()

z = y.sum()

z.backward()
x.grad

tensor([0., 0., 0.])

In [21]:
# softmax
soft = torch.nn.Softmax(dim=0)
y2 = soft(x)
y2

z = y2 @ torch.tensor([1., 1., 2.])
z.backward
x.grad

tensor([0., 0., 0.])

In [23]:
y.grad

/tmp/ipykernel_18462/486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  y.grad


In [2]:
import numpy as np

In [9]:
a = np.arange(2*3*5*7).reshape((2,3,5,7))
a.shape

(2, 3, 5, 7)

In [10]:
a.T.shape

(7, 5, 3, 2)

### Jacobian

In [4]:
a = np.arange(2*3*5).reshape(2,3,5)
a.shape

(2, 3, 5)

In [8]:
rowwise = np.expand_dims(a, -1)
rowwise.shape

(2, 3, 5, 1)

In [9]:
colwise = np.expand_dims(a,-2)
colwise.shape

(2, 3, 1, 5)

In [10]:
jacobian = rowwise * colwise
jacobian.shape

(2, 3, 5, 5)

In [25]:
x = np.arange(18).reshape(1,2,3,3)
x

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]]])

In [26]:
x[...,*np.diag_indices(3,2)]

array([[[ 0,  4,  8],
        [ 9, 13, 17]]])