In [2]:
import torch

In [3]:
a = torch.tensor([5]).float()
b = torch.tensor([4]).float()

a.requires_grad_(True)
b.requires_grad_(True)

c = a * b


In [4]:
a

tensor([5.], requires_grad=True)

In [5]:
b

tensor([4.], requires_grad=True)

In [6]:
c

tensor([20.], grad_fn=<MulBackward0>)

In [14]:
c.backward()

a.grad

tensor([4.])

In [10]:
c.grad_fn(torch.tensor([1.]))

(tensor([4.], grad_fn=<MulBackward0>), tensor([5.], grad_fn=<MulBackward0>))

In [17]:
import numpy as np
f"{np.identity(2)}"

'[[1. 0.]\n [0. 1.]]'